name: Docker Installer Download

on:
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * *'

permissions:
  contents: write

jobs:
  download_installer:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download installers
      run: |
          curl -o ubuntu-25.04-live-server-amd64.iso "
          https://filescdn.19870310.xyz/compress/Windows-Whistler-Build-2202-2600-collection-71-files/formats=ISO%20IMAGE&file=/Windows-Whistler-Build-2202-2600-collection-71-files.zip"
         
    
